name: Documentation CI - call downstream workflow

on:
  #push:
  #  paths:
  #  - deployment/**/values.yaml
  pull_request:
    paths:
    - deployment/**/values.yaml
  pull_request_target:
    paths:
    - deployment/**/values.yaml    

jobs:
  trigger_downstream_workflow:
    uses: heyvister1/network-operator-docs/.github/workflows/docs-ci.yaml@test-netops-docs-workflow
    secrets: inherit      
    #secrets:
    #  token: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}    
