name: Documentation CI - call downstream workflow

on:
  push:
    tags:
    - "v*"

jobs:
  trigger_downstream_workflow:
    uses: heyvister1/network-operator-docs/.github/workflows/docs-ci.yaml@fix-failed-doc-ci
    with:
      git_tag: ${{ github.ref_name }}
    secrets: inherit
